services:
  - type: web
    name: habit-tracker-server
    env: node
    buildCommand: "cd server && npm install"
    startCommand: "cd server && npm start"
    plan: free
    envVars:
      - key: DATABASE_URL
        scope: service

  - type: static
    name: habit-tracker-client
    buildCommand: "cd client && npm install && npm run build"
    publishPath: "client/dist"
    plan: free
    envVars:
      - key: VITE_API_URL
        value: "https://habit-tracker-server.onrender.com"

